# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  mandrill_username:  <%= ENV['MANDRILL_USERNAME'] %>
  mandrill_apikey:    <%= ENV['MANDRILL_APIKEY'] %>
  admin_email: <%= ENV['ADMIN_EMAIL'] %>
  secret_key_base: 54979b81acc61a36bbaa594ecf58ae4a3f1de0c8546debf28dfef57c808b1819cdddf51ac6bf1bdd7c1847a8a9573dd96c3e365b6ab16dd5a0f756f8ddcb8b55

test:
  secret_key_base: 10e910fffffd5bba804134d0b3e890e5c5ca0b9b699eb6b29044ec13d9a5534c6697b58d2e27c7b05ef627057cad2a39a9461a92c33d68cff1d9c8907a4394a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
